version: "3"
services:
  app:
    build:
      context: ./docker/flask
      dockerfile: Dockerfile
    ports:
      - 5000:5000
  neo4j:
    image: neo4j-image
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./data:/data
    environment:
      - NEO4J_AUTH=neo4j/xxxxxxxx
