version: "3"
services:
  neo4j:
    build:
      context: ./docker/neo4j
      dockerfile: Dockerfile
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./data:/data
      - ./docker/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/churchill
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"
        ]
      interval: 5s
      start_period: 10s
      retries: 5

  flask:
    build:
      context: ./docker/flask
      dockerfile: Dockerfile
    volumes:
      - ./docker/flask/app:/app
    depends_on:
      neo4j:
        condition: service_healthy

  svelte_kit:
    build:
      context: ./docker/svelte_kit
      dockerfile: Dockerfile
      # target: build
    volumes:
      - ./docker/svelte_kit/app:/app
    ports:
      - 3000:3000
    depends_on:
      neo4j:
        condition: service_healthy

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - svelte_kit
      - flask
