version: "3"
services:
  neo4j:
    image: neo4j:4.3.2
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./data:/data
      - ./docker/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/axP5GxoSa5
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1",
        ]
      interval: 5s
      start_period: 10s
      retries: 5

  svelte_kit:
    image: node:18-alpine
    command: npm run dev -- --host
    working_dir: /app
    volumes:
      - ./docker/svelte_kit/app:/app
    ports:
      - 5173:5173
    depends_on:
      neo4j:
        condition: service_healthy

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - svelte_kit
